import random
from datetime import datetime

nba_logo = """
.........................................
.........................................
.........................................
.........--=========-...:-------.........
......+#############.....:+#######=......
.....##############.......:########*.....
....##############=.......+#########=....
....##############+.......*#########+....
....##############+.....:###########+....
....#########*++--.....=############+....
....######*:............=###########+....
....#####+................-*########+....
....####*...................-#######+....
....###*.....................=######+....
....###-......................######+....
....##:..................:....######+....
....#=.................*##....*#####+....
....#.................-###=...-#####+....
....+................:####*....#####+....
....#=...............+#####:...=####+....
....###=..............-####*....+###+....
....##=................*####*....###+....
....##.................:#####=...*##+....
....##..................*#*-.......=+....
....##=.................*#..........:....
....###-................-:...............
....####:................:...............
....#####:...............*:.........=....
....######*-.............+#*:.....=*+....
....########-............:##########+....
....#########+............+#########+....
....##########*............+########+....
....############:...........*#######+....
....#############*..........:#######+....
....###############=.........*######+....
....#################-.......=######+....
....###################=.....-######+....
....#####################*:...=#####+....
....####..-*.*-...*#=..*##*....=####+....
....####...*.*-.#.:#=..*###:...+####+....
....####.:.=.*-.#.:#=-.+####...*####+....
....####.-:-:*-...+#.#=.####*..*####+....
....####.--:.*-.#.:#.+=.#####:.-####+....
....####.-*..*-.#.:#.+-.#####-.:####+....
....+###.-#:.*-...*..#+.-####...+###-....
.....+######################*....##=.....
.......+#####################-..*=.......
.........................................
.........................................
.........................................
"""

# List that stores all 30 present-day NBA teams
nba_teams = ["Philadelphia 76ers", "Milwaukee Bucks", "Chicago Bulls", "Cleveland Cavaliers", "Boston Celtics", "Los Angeles Clippers", "Memphis Grizzlies", "Atlanta Hawks",
 "Miami Heat", "Charlotte Hornets", "Utah Jazz", "Sacramento Kings", "New York Knicks", "Los Angeles Lakers", "Orlando Magic", "Dallas Mavericks", "Brooklyn Nets", "Denver Nuggets", 
 "Indiana Pacers", "New Orleans Pelicans", "Detroit Pistons", "Toronto Raptors", "Houston Rockets", "San Antonio Spurs", "Phoenix Suns", "Oklahoma City Thunder", "Minnesota Timberwolves",
 "Portland Trail Blazers", "Golden State Warriors", "Washington Wizards"
 ]

print(nba_logo)
print("Welcome to the NBA Stats Simulator! \n") 
startCareer = input("Would you like to start a career? Y or N\n").lower() # Allows user to input y or n

# Checks whether the user wants to begin career or not, or if user input is invalid and prompts again for correct input
while True:
    if startCareer == "y":
        random_team = random.randint(0, len(nba_teams) - 1)
        draft_team = nba_teams[random_team]
        round_pick = random.randint(1, 60)
        current_year = datetime.now().year
        draft_year = random.randint(1949, current_year)
        nba_year = draft_year
        rings = 0
        print(f"Congratulations, you have been drafted to the {draft_team} as the Round {round_pick} pick in the {draft_year} NBA Draft! \n")
        break

    elif startCareer == "n":
        print("Okay, goodbye!")
        break

    else: 
        print("Invalid input. ")
        startCareer = input("Would you like to start a career? Y or N\n").lower()

# Generates user's stats for the current NBA year and increases year by 1
def simulate_nba_year(draft_year, draft_team):
    global nba_year # Allows for non-local variable to be modified
    global rings # Allows for non-local variable to be modified

    # Random stats generated every time function is called
    points = random.uniform(0.0, 30.12)
    assists = random.uniform(0.0, 11.19)
    rebounds = random.uniform(0.0, 22.89)
    steals = random.uniform(0.0, 2.71)
    three_pt = random.uniform(0.0, 100.0)
    free_throw = random.uniform(0.0, 100.0)
    field_goal = random.uniform(0.0, 100.0)
    season_wins = random.randint(0, 82)
    season_losses = 82 - season_wins
    finals_winner = nba_teams[random.randint(0, len(nba_teams) - 1)]

    # Formats stats by 2 decimal places
    pt = "{:.2f}".format(points)
    asst = "{:.2f}".format(assists)
    reb = "{:.2f}".format(rebounds)
    stl = "{:.2f}".format(steals)
    threept = "{:.2f}".format(three_pt)
    ft = "{:.2f}".format(free_throw)
    fg = "{:.2f}".format(field_goal)

    print(f"In the {nba_year} NBA Season your team's record was {season_wins} - {season_losses}\nYou averaged: \n")
    print(f"{pt} points per game")
    print(f"{asst} assists per game")
    print(f"{reb} rebounds per game")
    print(f"{stl} steals per game")
    print(f"{threept}% 3-point field goals")
    print(f"{ft}% of free throws")
    print(f"{fg}% of field goals")
    
    # Checks whether or not your NBA team won the NBA Finals and prints a message based on that condition
    if finals_winner == draft_team:
        print(f"Your team won the {nba_year} NBA Finals!\n")
        rings +=1 # Increases rings by one if your team won the NBA Finals
    else:
        print(f"{finals_winner} won the {nba_year} NBA Finals!\n")
    nba_year += 1

simulate_nba_year(draft_year, draft_team)

# Prompts user for their decision to continue their career 
continueCareer = input("Would you like to continue your career? Y or N \n").lower()

# Generates user stats for years and prints concluding stats if user decides to retire
while True:
    if continueCareer == "y":
        simulate_nba_year(draft_year, draft_team)
        continueCareer = input("Would you like to continue your career? Y or N \n").lower()

    elif continueCareer == "n":
        num_seasons = (nba_year - draft_year) + 1
        print(f"You have retired!\nAfter playing from {draft_year} - {nba_year} ({num_seasons} NBA seasons), you won {rings} rings!\nI hope you enjoyed your career!")
        print("Thank you for playing the NBA Career Simulator!")
        break
    else:
        print("Invalid input.")
        continueCareer = input("Would you like to continue your career? Y or N \n").lower()
        
